skip_tags: true

image: Visual Studio 2019

platform: x86
configuration: Release

build:
  parallel: true
  project: PDA-Loader.sln

after_build:
    - cmd: publish

artifacts:
    - path: 1.01.7z
      name: 1.01
    - path: 3.01.7z
      name: 3.01
    - path: 6.00.7z
      name: 6.00