name: Build and upload release

on: 
  push:
    tags-ignore: '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
          msbuild -p:Configuration=Release
          cd .\source\plugins\MLAC
          msbuild -p:Configuration=101
          msbuild -p:Configuration=130
          msbuild -p:Configuration=301
          cd ..\..\..
          cmd publish
      - name: Add tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: none
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $tag
          files: |
            1.01.7z
            1.30.7z
            3.01.7z
            6.00.7z